<a href="https://colab.research.google.com/github/AnupamLata/Data-Science-AI/blob/main/Module_1_Python_Programming_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
name = "Anupam"
age = 25
salary = 63500
print(name)
print(age)
print(salary)


Anupam
25
63500


Assigning Values to varibales


1. Basic assignment

In [ ]:
x = 5
y = 3.14
z = "hi"
print(x)
print(y)
print(z)

5
3.14
hi


2. Dyanmic typing

In [ ]:
y = 10
x = "Anupam"
z = 2.4
print(type(y))
print(type(x))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>


3. Assigning Same Values

In [ ]:
a = b = c = 100
print(a, b, c)

100 100 100


4. Assigning Different Values

In [ ]:
x, y, z = 1, 2.5, "python"
print(x, y, z)

1 2.5 python


Numeric Data Type

1. Integer

In [ ]:
age = 25
print(type(age))

<class 'int'>


2. Flaot

In [ ]:
price = 99.99
print(type(price))

<class 'float'>


3. Complex

In [ ]:
x = 3+ 4j

print(x)
print(type(x))

(3+4j)
<class 'complex'>


Sequence Data Types

1. String

In [ ]:
s = 'Welcome to BBD '
print(type(s))

<class 'str'>


2. List

In [ ]:
a = [ 1, 2, 3]
print(a)
print(type(a))
b = ["BBD", "BBD", "BBD", 4, 5]
print(b)
print(type(b))

[1, 2, 3]
<class 'list'>
['BBD', 'BBD', 'BBD', 4, 5]
<class 'list'>


3. Tuples

In [ ]:
t1 = (1,)
print(type(t1))

t2 = ('BBD', 'BBD', 'BBD', 1, 2)
print(t2)
print(t2)



<class 'tuple'>
('BBD', 'BBD', 'BBD', 1, 2)
('BBD', 'BBD', 'BBD', 1, 2)


Set Data Type

Set

In [ ]:
s1 = {"a", "a", "b", "c", "b"}
print(s1)

s2 = {"BBD", "FOR", "BBD"}
for i in s2:
  print(i)

{'b', 'a', 'c'}
FOR
BBD


#Dictionary Data Type


In [ ]:
d = {1: 'BBD', 2: 'For', 3: 'BBD'}
print(d[1])
print(d.get(2))

BBD
For


#Operators

1. Arithmetic Operator

In [ ]:
a = 15
b = 4

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modules:", a % b)
print("Exponentiation:", a ** b)



Addition: 19
Subtraction: 11
Multiplication: 60
Division: 3.75
Floor Division: 3
Modules: 3
Exponentiation: 50625


2. Comparision Operator

In [ ]:
a = 13
b = 33

print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

False
True
False
True
False
True


3. Logical Operators

In [ ]:
a = True
b = False
print(a and b)
print(a or b)
print(not a)

False
True
False


4. Bitwise operator

In [ ]:
a = 10
b = 4
print(~a)
print(a << b)
print(a & b)
print(a ^ b)
print(a | b)
print(a >> b)

-11
160
0
14
14
0


5. Assignment Operators

In [ ]:
a = 10
b = a
print(b)
b += a
print(b)
b -= a
print(b)
b *= a
print(b)
b <<= a
print(b)


10
20
10
100
102400


6. Identity Operator

In [ ]:
a = 10
b = 20
c = a

print(a is not b)
print(a is c)



True
True


7. Membership Opertors

In [ ]:
x = 24
y = 20
my_list = [10, 20, 30, 40, 50]

if (x not in my_list):
  print("x is NOT present in given list")
else:
  print("x is present in given list")
if (y in my_list):
  print("y is present in given list ")
else:
  print("y is Not present in given list")

x is NOT present in given list
y is present in given list 


8. Ternary Operator

In [ ]:
a, b = 10, 20
min = a if a < b else b

print(min)

10


Q.1 Take two numbers as input from the user and perform all arithmetic Operations.

In [ ]:
a = 18
b = 3

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modules:", a % b)
print("Exponentiation:", a ** b)


Addition: 21
Subtraction: 15
Multiplication: 54
Division: 6.0
Floor Division: 6
Modules: 0
Exponentiation: 5832


2 . Check whether a specific course is available in the course catalog

In [ ]:
courses = ["python", "Java", "C++", "Data Science"]
course = input("enter course name: ")
if course in courses:
  print("Course is available")
else:
  print("Course is not available")


enter course name: java
Course is not available


3. Create a simple login validation system using a username and password

In [ ]:
username = input("Enter username:")
password = input("Enter password:")

if username == "AnupamLata" and password == "1234":
  print("Login Successful")
else:
  print("Invalid Username or Password")

Enter username:AnupamLata
Enter password:1234
Login Successful


4. An employee is eligible for a bonus only if : salary is greater than 30000 experience is greater than 2 years write a program to determin eligility.

In [ ]:
salary = float(input("Enter salary: "))
experience = float(input("Enter experience (years):"))

if salary > 30000 and experience > 2:
  print("Eligible for bonus")
else:
  print("Not Eligible for bonus")


Enter salary: 500000
Enter experience (years):3
Eligible for bonus


#Conditional Statements

1. If Statement

In [ ]:
age  = 22
if age >= 18:
  print("eligible to vote")

eligible to vote


short-hand if

In [ ]:
age = 19
if age > 18 :
  print("eligible to vote")


eligible to vote


2. If else Statement

In [ ]:
age = 10
if age <= 12:
  print("Travel for free.")
else:
  print("Pay for ticket.")

Travel for free.


3. If-elif-else statement

In [ ]:
age = 25
if age <= 12:
  print("child.")
elif age <= 19:
  print("Teenager.")
elif age <= 35:
  print("Young adult")
else:
  print("Adult")

Young adult


4. Nested if-else statement

In [ ]:
age = 70
is_member = True

if age >= 60:
  if is_member:
    print("30% senior discount!")
  else:
    print("20% senior discount!")
else:
   print("Not eligible for a senior discount.")


30% senior discount!


#Loops

1.  For Loop

In [ ]:
for i in range(1,6):
  print(i)


1
2
3
4
5


Example 2 : Iterate through a LIST


In [ ]:
fruits = ["Apple", "Banana", "Mango"]

for fruit in fruits:
  print(fruit)

Apple
Banana
Mango


2. While Loop

In [ ]:
count = 1
while count <= 5:
  print(count)
  count += 1


1
2
3
4
5


3. Loop control Statements

A. break

In [ ]:
for i in range(1, 10):
  if i == 5:
    break
  print(i)

1
2
3
4


B . continue

In [ ]:
for i in range(1,6):
  if i == 3:
    continue

  print(i)

1
2
4
5


C  . pass

In [ ]:
for i in range(5):
  pass

print("Loop completed")

Loop completed


4. Nested Loops

In [ ]:
for i in range(1,4):
  for j in range (1, 4):
    print(i,j)

1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3


# Questions on conditions and loops

Q.1 Take a number from the user and calculate the sum of all numbers from 1 to N.

In [ ]:
n = int(input("Enter N: "))
sum = 0

for i in range (1, n+1):
  sum += i

print("Sum = " , sum)



Enter N: 3
Sum =  6


Q.2 Allow the user to enter a password until the correct password is Entered.

In [ ]:
from pathlib import PureWindowsPath
correct_password = "Anupam016"

while True:
  password = input("Enter Password:")

  if password == correct_password:
    print("access Granted")
    break
  else:
    print("Wrong Password")

Enter Password:jhgf
Wrong Password
Enter Password: mnbv
Wrong Password
Enter Password:
Wrong Password
Enter Password:1234
Wrong Password
Enter Password:Anupam016
access Granted


Q.3 find how many positive numbers are present in a list.

In [ ]:
numbers = [10, -5, 0, 7, -2, 15, -8]

count = 0
for num in numbers:
  if num > 0:
    count += 1

print("Number of positive numbers: ", count)


Number of positive numbers:  3


Q.4 Check whether monthly sales achieved the target.

In [ ]:
target = 60000
sales = int(input("Enter monthly sales : "))

if sales >= target:
  print("Target achieved ")
else:
  print("Target Not Achieved ")

Enter monthly sales : 55555
Target Not Achieved 


Q.5 Print all even number between 1 and 50 using a loop.

In [ ]:
for i in range(1, 51):
  if i % 2 == 0:
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


#Functions

In [ ]:
def greet():
  print("Welcome to BBD")
greet()


Welcome to BBD


2. Function with Parameters

In [ ]:
def greet(name):
  print("Hello" , name)

greet("Anupam")

Hello Anupam


3. Function with Mutliple parameters

In [ ]:
def add(a, b):
  print(a + b)

add(10, 20)


30


4 . Function with  return Statement

In [ ]:
def square(num):
  return num * num

result = square(5)

print(result)

25


5. Default Parameters

In [ ]:
def country (name = "India"):
  print("country :", name)

country ()
country("USA")



country : India
country : USA


6. Keyword Arguments

In [ ]:
def student(name, age):
  print(name, age)

student(age = 22, name = "Anupam")


Anupam 22


7. Variable length arguments(*args)


In [ ]:
def total(*numbers):
  print(sum(numbers))

total(10, 20, 30)


60


8. Keyword Variable Arguments (**kwargs)

In [ ]:
def info(**details):
  print(details)

info(name = "Anupam", city = "Lucknow")


{'name': 'Anupam', 'city': 'Lucknow'}


9. lambda function

In [ ]:
square = lambda x : x*x

print(square(6))

36


10. Functions with Lists

In [ ]:
def average(numbers):
  return sum (numbers)/ len(numbers)

data = [10, 20, 30, 40, 50]

print(average(data))


30.0


Q 1. create a function that calculates the final salary of an employee after adding bonus and deducting tax.

In [ ]:
def calculate_final_salary(basic_salary, bonus, tax):
  final_salary = basic_salary + bonus - tax
  return final_salary

salary = calculate_final_salary(50000, 5000, 3000)

print("Final Salary :" , salary)



Final Salary : 52000


Q 2. Create a function that accepts marks of multiple subjects using *args and calculates total, average, and grade.

In [ ]:
def calculate_result (*marks):
  total = sum(marks)
  average = total / len(marks)

  if average >= 90:
    grade = "A+"
  elif average >= 80:
    grade = "A"
  elif average >= 70:
    grade = "B"
  elif average >= 60:
    grade = "C"
  elif average >= 50:
    grade = "D"
  else:
    grade = "F"

  print("Total Marks: ", total)

  print("Average Marks: ", average)

  print("Grade: ", grade)

calculate_result (85, 90, 78, 88, 92)



Total Marks:  433
Average Marks:  86.6
Grade:  A


Q 3. customer information Management System
use **kwargs to store customer details dynamically.

In [ ]:
def customer_info(**kwargs):
  print("Customer Details:")
  for key, value in kwargs.items():
    print(f"{key} : {value}")


customer_info(
    Name = "Anupam",
    Age = 21,
    City = "Lucknow",
    Email = "yanu77662@gmail.com",
    Phone = "7600969707"
)


Customer Details:
Name : Anupam
Age : 21
City : Lucknow
Email : yanu77662@gmail.com
Phone : 7600969707


#File Handling in Python

1.Opening a file

In [ ]:
file = open("/content/data.txt", "r", encoding = 'latin-1')
print(file.read())
file.close()


PK-Š~±XQ5aßÿÿÿÿÿÿÿÿ	input.txtí¿Œ½ËvÛX²-ÚÇW@-v(}ÕАé²öq¦óÚªòÈ&H,’H1Y_bÎk\ûÜ1öΒ%XxnjˆOU×ùÇj¨þšMö!ìÛ.䗐Ÿ»vB™Í5ߏÝpÝ:?†¢ËO!ïÏ¡x¹Ë²ÇºÞdßñuúݛ'þَya,ê:ïBßÖ¯öЮÀóò¡ÍË*äñhðó¾8UýñÁûÍ?|—¾öþáüç:¿Ú;^šö’,ª±Ï+ºþ·êóݱ
û<4átÅì­ù9´ç:ÄÅÿüæʞr‰?¾ϗ0äöÀ—Ê6q¬Nk;•Ò>¿Â?‹×ïڮɋ!oÇ.o/^µ³W<õ«!/ò×ЕÕnˆû½ÍO8䡨_ªæ·Íj¸Ïk{E5äې—m6yq)®kþ÷&˾‡]koLëùÚص]¹Îm[æ;ý¾¿pÛ·kÇf°“?·m—>¿Öƒ-·*šžO»Ë~m+Å8Û®®y?vûP
½-Ô^:Öv}¡®‚m{ì7yµÇC®™þr­‚ý׎j;|x?žC·¯G{ð±ªvy	]È.Ƕ¶›=ý©:‡ü0†¾çãKø´ãx*šP_ï3®Ýæ±j^ðEìoh’Œ67|gŠ¦ÑsŠ!+öûÚN¿·çh¿íö¯°³»ÚóºŒäBgk3b)ìÿš¬j^C3´	æ\tCµ뢳áÛU—Û±)‹fîñ€¬÷ûÐáß|F~(ªÆií”;át¶‘æ€ØG.ÕpÌðêsõlMA·µ;6Öê
ûå&76äbmً¶Ÿ2r˜ža¯8ŽöĎÜv¡0ZhÚ°€ðïÝ{
ú¡ë2ƉŒìñFu}Íìd4g§H¾þGãƒ|7mL,¬zÑùÕ¨÷9Íösj›¢®?YÀǶé«Ò6€5\@qv¯Æ6vÛÁ¸ª'pØ0é·»>¼£ðᥗP×÷dÊ÷µÅˍޛk9TF«X.È;ë¹íx<Æó"'{9ùàÚãc}¨÷¼${øÓh,²ƒßÁ x€î§*ŒÔªvìëë{^|ÊûâšÛ6Zìy­Ms¯ö*m¶8ñ»´&ˬt–öÁД îv<ó¾Ý·¶˜~W£»ÒDr“ïLˆnC6Û7^f³³|sŒþüœÏÏL}àßO-3NÒ°
d£žÁ=xw´/gèÖh+ qÙvÍÕ0–|…'½VÝ0þ

Polymorphism

In [ ]:
class animal:
  def sound (self):
    print("Animal makes a sound")



Abstraction

In [ ]:
from abs import ABC, abstractmethod

class Vehicle(ABC):

  @abstractmethod
  def start(self):
    pass

class Car(Vehicle):

  def start(self):
    print("Car start ")


#NumPy


1. Installing Numpy

In [1]:
pip install numpy

import NumPy

In [2]:
import numpy as np

2. Creating Numpy Arrays

from a list

In [4]:
import numpy as np
arr = np.array([10,20,30, 40, 50])

print(arr)
print(type(arr))


[10 20 30 40 50]
<class 'numpy.ndarray'>


4. Two- Dimensional Array(2D)

In [5]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


#5. Three-Dimensional array(3D)


In [7]:
import numpy as np
arr = np.array([
  [[1,2], [3,4]],
  [[5,6], [7,8]]
  ])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#6. Array Attributes
NumPy array attributes provide important information about an array, such as its dimensions, size , shape, and data types

In [8]:
import numpy as np
arr =np.array([[1,2,3], [4,5,6]])

print("Shape:" , arr.shape)
print("dimensionn :", arr.ndim)
print("size:",arr.size)
print("Data Type:",arr.dtype)



Shape: (2, 3)
dimensionn : 2
size: 6
Data Type: int64
